# Generated by Django 4.1.2 on 2022-11-06 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Цикл')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='book_covers', verbose_name='Обложка')),
                ('isbn', models.BigIntegerField(db_index=True, verbose_name='ISBN')),
                ('published', models.DateField(blank=True, default=None, null=True, verbose_name='Дата публикации')),
                ('annotation', models.TextField(verbose_name='Аннотация')),
                ('rating', models.IntegerField(blank=True, default=None, null=True, verbose_name='Рейтинг')),
                ('first_reading', models.DateField(blank=True, default=None, null=True, verbose_name='Первое прочтение')),
                ('second_reading', models.DateField(blank=True, default=None, null=True, verbose_name='Второе прочтение')),
                ('third_reading', models.DateField(blank=True, default=None, null=True, verbose_name='Третье прочтение')),
                ('author', models.ManyToManyField(related_name='book', to='books.author', verbose_name='Автор')),
                ('cycle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.cycle', verbose_name='Цикл')),
                ('genre', models.ManyToManyField(related_name='book', to='books.genre', verbose_name='Жанр')),
                ('series', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.series', verbose_name='Серия')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
