# Generated by Django 4.1.2 on 2022-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='author',
            name='death',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
