# Generated by Django 4.1.2 on 2022-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookcategory_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='book', to='books.bookcategory', verbose_name='Категория'),
        ),
    ]
