# Generated by Django 4.1.2 on 2022-12-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stripe_book_price_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Price id книги в Stripe'),
        ),
    ]
