# Generated by Django 4.1.2 on 2022-12-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_text_alter_book_rating_alter_book_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Читаю'), (1, 'Закончена'), (2, 'Буду читать'), (3, 'Заинтересовала'), (4, 'Заброшена')], default=1, verbose_name='Статус'),
        ),
    ]
